# Generated by Django 5.2.4 on 2026-04-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_alter_customuser_numero_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('responsable', 'Responsable'), ('client', 'Client')], max_length=20),
        ),
    ]
