# Generated by Django 5.2.4 on 2026-05-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=32)),
                ('cell_lat', models.DecimalField(db_index=True, decimal_places=6, max_digits=10)),
                ('cell_lon', models.DecimalField(db_index=True, decimal_places=6, max_digits=11)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('sector_main', models.CharField(db_index=True, max_length=128)),
                ('entity_count_real', models.IntegerField(default=0)),
                ('entity_count_total', models.IntegerField(default=0)),
                ('density_log', models.FloatField(default=0.0)),
                ('active_rate', models.FloatField(default=0.0)),
                ('capital_median', models.FloatField(default=0.0)),
                ('capital_mean', models.FloatField(default=0.0)),
                ('capital_max', models.FloatField(default=0.0)),
                ('sector_diversity', models.FloatField(default=0.0)),
                ('formal_ratio', models.FloatField(default=0.0)),
                ('sarl_count', models.IntegerField(default=0)),
                ('sa_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['cell_id', 'sector_main'],
                'indexes': [models.Index(fields=['city', 'sector_main'], name='entreprise__city_91efe7_idx'), models.Index(fields=['cell_id', 'sector_main'], name='entreprise__cell_id_aea52c_idx')],
                'unique_together': {('cell_id', 'sector_main')},
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(db_index=True, max_length=512)),
                ('sector', models.TextField(blank=True)),
                ('sector_main', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(blank=True, max_length=128)),
                ('legal_form', models.CharField(blank=True, max_length=128)),
                ('company_status', models.CharField(db_index=True, max_length=64)),
                ('capital_dhs', models.FloatField(default=0.0)),
                ('activity', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=11)),
                ('source_dataset', models.CharField(blank=True, max_length=64)),
                ('geo_cell_key', models.CharField(blank=True, db_index=True, max_length=32)),
                ('economic_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to='entreprise.economiccell')),
            ],
            options={
                'ordering': ['entity_name'],
                'indexes': [models.Index(fields=['city', 'sector_main'], name='entreprise__city_82b340_idx'), models.Index(fields=['geo_cell_key'], name='entreprise__geo_cel_e17aba_idx'), models.Index(fields=['latitude', 'longitude'], name='entreprise__latitud_d7e16b_idx')],
            },
        ),
    ]
