# Generated by Django 5.2.4 on 2026-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_customuser_is_premium_customuser_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='economiccell',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='economiccell',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='economiccell',
            name='region_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='economiccell',
            name='zone_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='economiccell',
            index=models.Index(fields=['display_name'], name='entreprise__display_a72d57_idx'),
        ),
        migrations.AddIndex(
            model_name='economiccell',
            index=models.Index(fields=['region_name', 'city'], name='entreprise__region__d015cd_idx'),
        ),
    ]
